# This is a basic workflow to help you get started with Actions

name: hola-mundo
# Controls when the workflow will run
on: [push]
jobs:
  hola-mundo: 
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v4
      # Runs a single command using the runners shell
      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with: 
          python-version: "3.11"
      - name: script-runing
        run: python print-hola-mundo.py 

      
